### ISSUE TITLE
Issue when users send messages in guild chat

### ISSUE THREAD

**Issue by NightCrafter1** [mew/discord-hypixel-bridge#1]
Whenever a user sends a message in guild chat I get this error and it crashes.
![image](https://user-images.githubusercontent.com/64771089/107179814-30334c80-6a23-11eb-955c-964c87b671c1.png)

**Comment by mew** [comment]
bro i really havent looked at the code for this in 15 months

**Comment by NightCrafter1** [comment]
oh sorry XD
i found what the issue was though

**Comment by NightCrafter1** [comment]
any way i can blacklist the bot for resending its own messages back to discord?

**Comment by NightCrafter1** [comment]
Don't worry i figured it out myselff
